### ISSUE TITLE
jekyll-sitemap LoadError

### ISSUE THREAD

**Issue by developius** [PiNet/PiNet.github.io#8]
I've installed all the dependencies by running `bundle install --binstubs` but when I try and run the docs locally using `jekyll serve watch`, I get this error:

```
/[...]/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-sitemap (LoadError)
```

What am I doing wrong?

**Comment by gbaman** [comment]
Try running it with
`./bin/jekyll serve watch`
As that uses the plugins in the bin folder instead of searching your system. Welcome to the joys of Ruby plugins...

**Comment by developius** [comment]
Yeah thanks that works!

**Comment by developius** [comment]
Yeah thanks that works!
