### ISSUE TITLE
URL Shorteners

### ISSUE THREAD

**Issue by Dodgson-here** [PiNet/PiNet.github.io#9]
I'm looking into this software as a possible solution for using Pi's in my school.  The documentation and instructions make significant use of URL shorteners.  URL shorteners are blocked by default in most filtering systems and many IT departments view them as a security risk.  This makes it very difficult to find the referenced file or to follow command line instructions in the documentation.

Please consider changing links to actual locations.

**Comment by gbaman** [comment]
Correct, PiNet makes use of bit.ly in a number of places for metrics. In the many hundreds of PiNet school installs, I have yet to hear of any school that had issues with using bit.ly, especially given it is basically the worlds most popular URL shortener. If a school does not have access to bit.ly, it is unlikely to have access to many of the other domains used by PiNet. In that case, usually educators simply take the server machine home and install it using their home internet connection.
As such, I have no intention of changing this.
